### ISSUE TITLE
Add ability to show UTC offset for users

### ISSUE THREAD

**Issue by cvuorinen** [midblue/timezone-bot#32]
Wondering why outputting the UTC offset has been commented out from the command that lists all users timezones? Seems like good info to me and we would like to see that in our server at least. Could be added back, or make a setting to enable/disable it or something?

https://github.com/midblue/timezone-bot/blob/7bc0f5c84f76fba8f2bc00a5fd4805a04deb5813/commands/all.js#L93-L97

**Comment by midblue** [comment]
I commented it out because the offset changes over time, and the number I have saved in the database isn't always truly accurate.
i.e. for Eastern Time, sometimes its offset is sometimes -4. and sometimes -5. Really, the "offset" param shouldn't even be saved, just the location so that I can get an accurate and up-to-date value each time.

**Comment by midblue** [comment]
I've changed the way I calculate these, and they're accurate again! Readded.
