### ISSUE TITLE
!user creates unsorted output

### ISSUE THREAD

**Issue by HiromiCota** [midblue/timezone-bot#4]
Although the output correctly reduces people by timezone, the timezones themselves are unsorted. The usernames also appear to be unsorted. 

I don't understand JS nearly well enough to figure out what's going on. I'd love to help, though. Thanks.

<img width="490" alt="Screen Shot 2019-06-18 at 2 31 08 AM" src="https://user-images.githubusercontent.com/24899665/59670762-4e26ac00-9171-11e9-84e0-a61ef4c114c2.png">

**Comment by midblue** [comment]
Interesting! I'll take a look at that soon. It always appear sorted on my server, so there must be something tricky going on.

**Comment by midblue** [comment]
In scripts/interact.js, it's either one of two things. I don't have a great dev environment at the moment, but...
1. It might be sort issues on line 85: `.sort((a, b) => a.offset > b.offset)`. I've seen JS sort do weird things with greater than symbols, so maybe flipping the operands and changing to a minus sign would fix it.
2. it also might be odd object ordering in line 89: `acc[timezoneName] = {`, which is then used on line 99: `const outputString = Object.values(timezonesWithUsers)`. If somehow the object doesn't preserve the order in which things were entered, it might be worth changing acc into an array rather than an object so that it forces a certain order. of course, you'd have to store the timezoneName as a property on the object within each element of the array.
Does that help?

**Comment by nemato1** [comment]
The sorting still hasn't been able to be fixed. In addition, based on what month of the year a user sets their time zone with the bot it will save as Standard or Daylight, but not adjust based on what time of the year it currently is. The time itself is correct for both, it just has people separated based on when they joined the channel.

![Screenshot_20200510-140628](https://user-images.githubusercontent.com/64911130/81507190-9c80f400-92c9-11ea-963b-dc39c3fccbfa.png)

**Comment by nemato1** [comment]
@midblue I am in the same server as HiromiCota. Is there any update that could fix either issue for us?

**Comment by midblue** [comment]
@nemato1 Hi! I just pushed an update that should fix both of these, but my testing environment is limited. Thanks for the bug report, and sorry it took so long to get to this!
Please let me know if my changes fix your issues, since I can't seem to reproduce it on my end.

**Comment by HiromiCota** [comment]
Looks like it solves the problem! Thanks a lot, Jasper!

**Comment by midblue** [comment]
Excellent! Glad to hear it.
